# Generated by Django 3.2.16 on 2025-11-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='field1',
            field=models.CharField(default='default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='field2',
            field=models.CharField(default='default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='field3',
            field=models.CharField(default='default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='field4',
            field=models.CharField(default='default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='field1',
            field=models.CharField(default='default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='field2',
            field=models.CharField(default='default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='field3',
            field=models.CharField(default='default_value', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
